name: Test
on:
  workflow_dispatch:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2.4.2

      - name: Test
        shell: bash
        run: |
          # git show-branch -a 2>/dev/null
          echo A
          A=$(git show-branch -a)
          echo B
          B=$(git show-branch -a | grep '\*')
          echo C
          C=$(git show-branch -a | grep '\*' | grep -v `git rev-parse --abbrev-ref HEAD`)
          echo D
          D=$(git show-branch -a | grep '\*' | grep -v `git rev-parse --abbrev-ref HEAD` | head -n1)
          echo E
          E=$(git show-branch -a | grep '\*' | grep -v `git rev-parse --abbrev-ref HEAD` | head -n1 | sed 's/.*\[\(.*\)\].*/\1/')
          echo PB
          PARENT_BRANCH=$(git show-branch -a | grep '\*' | grep -v `git rev-parse --abbrev-ref HEAD` | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')
          echo $PARENT_BRANCH
