name: Test
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2.4.2

      - name: Test
        shell: bash
        env:
          # github.ref_name is the name of the branch on push, and the tag on tag
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          PARENT_BRANCH=$(php -r '
            preg_match_all("#\*.+\[(.+?)\]#", shell_exec("git show-branch -a 2>/dev/null"), $m);
            return array_merge(array_filter($m[1], function($v) { return $v != "${{ env.GITHUB_REF_NAME }}"; }))[0] ?? "";
          ')
          echo $PARENT_BRANCH
