name: Test
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2.4.2

      - name: Test
        shell: bash
        run: |
          # Note: { grep * || :; } is to prevent exit code of 1 on zero-match from halting workflow
          echo A
          echo $(git show-branch -a 2>/dev/null)
          echo B
          echo $(git show-branch -a 2>/dev/null | { grep \* || :; })
          echo C
          echo $(git show-branch -a 2>/dev/null | { grep \* || :; } | { grep -v `git rev-parse --abbrev-ref HEAD` || :; })
          echo D
          echo $(git show-branch -a 2>/dev/null | { grep \* || :; } | { grep -v `git rev-parse --abbrev-ref HEAD` || :; } | head -n1)
          echo E
          echo $(git show-branch -a 2>/dev/null | { grep \* || :; } | { grep -v `git rev-parse --abbrev-ref HEAD` || :; } | head -n1 | sed 's/.*\[\(.*\)\].*/\1/')
          echo F
          PARENT_BRANCH=$(git show-branch -a 2>/dev/null | { grep \* || :; } | { grep -v `git rev-parse --abbrev-ref HEAD` || :; } | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')
          echo $PARENT_BRANCH

