name: Test
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
            
      - name: Checkout code
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2.4.2

      - name: Test
        shell: bash
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}          
        run: |
          echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          if [[ "${{ github.event_name }}" == "pull-request" ]]; then
            echo github.event.pull_request
            echo github.event.pull_request.pull_request
            echo github.event.pull_request.pull_request.commits
          fi
